version: '3.8'
services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # API AdonisJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "${PORT}:${PORT}" # Usa a porta definida no .env
    env_file:
        - .env #
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  postgres_data:
